language: java
notifications:
    recipients:
        -dimitris214@yahoo.gr
branches:
  only:
    - master
install: true
script: 
    - javac -cp munit.jar Lab01Test.java
    - java -jar munit.jar lab01.asm Lab01Test.class
